name: Build and Upload Kernel

on:
  workflow_dispatch: # เปิดให้กดปุ่มสั่งรันด้วยมือ (Manual) ได้จากหน้าเว็บ GitHub
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Clone Full Kernel Source Tree
        uses: actions/checkout@v4
        with:
          repository: 'tcburakdemir/samsung-r0q-resukisu-kernel'
          depth: 1

      - name: Inject Safe System Path
        run: |
          echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV

      - name: Run Samsung Kernel Build Script
        run: |
          chmod +x build_kernel_GKI.sh
          ./build_kernel_GKI.sh

      # --- ขั้นตอนสำหรับการอัปโหลดไฟล์ ---
      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Samsung-S22-Resukisu-Kernel # ตั้งชื่อไฟล์ดาวน์โหลดบนหน้าเว็บ
          path: |
            out/arch/arm64/boot/Image
            out/*.zip
          if-no-files-found: warn
